#--------- https://t.me/AntonyAbotSchool --- where people are always newbies -----#
version: "3"
services:
    nginx:
        image: nginx:1.22.0-alpine
        ports:
            - 80:80
            - 8080:8080
        restart: always
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        links:
            - php-5
            - php-7
            - php-8
            - phpmyadmin
    php-5:
        image: php:5.6.40-fpm-alpine3.8
        volumes:
            - ./www:/var/www/html
            - ./php5.6/usr/local/etc/php-fpm.d:/usr/local/etc/php-fpm.d
    php-7:
        image: php:7.4.30-fpm-alpine3.16
        volumes:
            - ./www:/var/www/html
            - ./php7.4/usr/local/etc/php-fpm.d:/usr/local/etc/php-fpm.d
    php-8:
        image: php:8.1.7-fpm-alpine3.16
        volumes:
            - ./www:/var/www/html
            - ./php8.1/usr/local/etc/php-fpm.d:/usr/local/etc/php-fpm.d
    sql:
        image: jbergstroem/mariadb-alpine:10.6.8
        restart: on-failure
        volumes:
            - ./sql-mariadb:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect="SET NAMES UTF8;" --innodb-flush-log-at-trx-commit=0
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
    phpmyadmin:
        image: phpmyadmin:5.2.0-fpm-alpine
        restart: on-failure
        depends_on:
            - sql
        environment:
            PMA_HOST: sql
            MYSQL_ROOT_PASSWORD: root
